export class BladeErrorCodes {
    static readonly TYPE_UNEXPECTED_END_OF_INPUT = 'BLADE_001';
    static readonly TYPE_PARSE_UNCLOSED_CONDITION = 'BLADE_002';
    static readonly TYPE_PARSE_UNCLOSED_SWITCH = 'BLADE_003';
    static readonly TYPE_UNPAIRED_CLOSING_DIRECTIVE = 'BLADE_004';
    static readonly TYPE_UNCLOSED_COMMENT = 'BLADE_005';
    static readonly TYPE_UNCLOSED_PHP_DIRECTIVE = 'BLADE_006';
    static readonly TYPE_UNPAIRED_PHP_CLOSING_DIRECTIVE = 'BLADE_007';
    static readonly TYPE_UNCLOSED_VERBATIM = 'BLADE_008';
    static readonly TYPE_UNPAIRED_VERBATIM_CLOSING_DIRECTIVE = 'BLADE_009';
    static readonly TYPE_UNCLOSED_FOR_DIRECTIVE = 'BLADE_010';
    static readonly TYPE_UNPAIRED_FOR_CLOSING_DIRECTIVE = 'BLADE_011';
    static readonly TYPE_UNCLOSED_FOR_ELSE_DIRECTIVE = 'BLADE_012';
    static readonly TYPE_UNPAIRED_FOR_ELSE_CLOSING_DIRECTIVE = 'BLADE_013';
    static readonly TYPE_FOR_ELSE_MISSING_EMPTY_DIRECTIVE = 'BLADE_014';
}